update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -64,14 +64,14 @@ build_prod_image:
   needs: [build_prod_dependencies]
   only:
     - tags
-#
-#cs:
-#  stage: test
-#  image: $DEV_IMAGE
-#  variables:
-#    GIT_STRATEGY: none
-#  script:
-#    - ./vendor/bin/php-cs-fixer fix src --dry-run --stop-on-violation
+
+cs:
+  stage: test
+  image: $DEV_IMAGE
+  variables:
+    GIT_STRATEGY: none
+  script:
+    - ./vendor/bin/php-cs-fixer fix src --dry-run --stop-on-violation
 
 phpunit:
   stage: test
@@ -101,51 +101,51 @@ phpunit:
         coverage_format: cobertura
         path: coverage.cobertura.xml
 
-#composer:
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - composer normalize --diff --dry-run # https://github.com/ergebnis/composer-normalize
-#    - composer validate # https://getcomposer.org/doc/03-cli.md#validate
-#    - vendor/bin/composer-require-checker check --config-file=composer-require-checker.json # https://github.com/maglnet/ComposerRequireChecker
-#    - php8.2 vendor/bin/composer-unused # https://github.com/composer-unused/composer-unused
-#    - composer audit # https://getcomposer.org/doc/03-cli.md#audit
-#    - composer check-platform-reqs
-#
-#psalm:
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - vendor/bin/psalm
-#
-#di: # чтобы проверить, что контейнер компилируется корректно в прод режиме
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - bin/console cache:clear --env=prod
-#    - bin/console lint:container --env=prod
-#
-#schema-validate: # проверить корректность маппингов доктрины, без соединения с бд
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - bin/console doctrine:schema:validate --skip-sync
-#
-#rector:
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - vendor/rector/rector/bin/rector --dry-run
+composer:
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - composer normalize --diff --dry-run # https://github.com/ergebnis/composer-normalize
+    - composer validate # https://getcomposer.org/doc/03-cli.md#validate
+    - vendor/bin/composer-require-checker check --config-file=composer-require-checker.json # https://github.com/maglnet/ComposerRequireChecker
+    - php8.2 vendor/bin/composer-unused # https://github.com/composer-unused/composer-unused
+    - composer audit # https://getcomposer.org/doc/03-cli.md#audit
+    - composer check-platform-reqs
+
+psalm:
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - vendor/bin/psalm
+
+di: # чтобы проверить, что контейнер компилируется корректно в прод режиме
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - bin/console cache:clear --env=prod
+    - bin/console lint:container --env=prod
+
+schema-validate: # проверить корректность маппингов доктрины, без соединения с бд
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - bin/console doctrine:schema:validate --skip-sync
+
+rector:
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - vendor/rector/rector/bin/rector --dry-run
 
 check_coverage:
   image: alpine:latest # you should use PAT cuz JOB_TOKEN doesnt have sufficient permissions
@@ -223,154 +223,154 @@ check_coverage:
           echo "Coverage check passed: ${CURRENT_COVERAGE}% (previous: ${TARGET_COVERAGE}%)";
         fi
       fi
-#
-#migrations_rollback_test:
-#  stage: test
-#  image: $DEV_IMAGE
-#  services:
-#    - name: postgres:14
-#      alias: postgres
-#  variables:
-#    APP_ENV: test
-#    DATABASE_URL: "pgsql://postgres:postgres@postgres:5432/test_db"
-#    POSTGRES_DB: test_db
-#    POSTGRES_USER: postgres
-#    POSTGRES_PASSWORD: postgres
-#    GIT_STRATEGY: none
-#  script:
-#    - apt-get update && apt-get install -y postgresql-client
-#    - until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done
-#    - bin/console doctrine:database:create --if-not-exists --env=test
-#    - bin/console doctrine:migrations:migrate --no-interaction --env=test
-#    - bin/console doctrine:migrations:migrate first --no-interaction --env=test
-#    - bin/console doctrine:migrations:migrate --no-interaction --env=test
-#
-#phpmd:
-#  stage: test
-#  image: $DEV_IMAGE
-#  variables:
-#    GIT_STRATEGY: none
-#  script:
-#    - vendor/bin/phpmd src json phpmd.xml --reportfile phpmd_result.json
-#  artifacts:
-#    when: always
-#    paths:
-#      - phpmd_result.json
-#
-#deptrac:
-#  variables:
-#    GIT_STRATEGY: none
-#  stage: test
-#  image: $DEV_IMAGE
-#  script:
-#    - vendor/bin/deptrac --config-file=deptrac.modules.yaml --cache-file=var/.deptrac.modules.cache
-#    - vendor/bin/deptrac --config-file=deptrac.directories.yaml --cache-file=var/.deptrac.directories.cache
-#
-#kics-iac-scan:
-#  stage: test
-#  image:
-#    name: checkmarx/kics:latest
-#    entrypoint: [""]
-#  script:
-#    - kics scan --no-progress -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results
-#  artifacts:
-#    when: always
-#    name: kics-results.json
-#    paths:
-#      - kics-results.json
-#
-#trivy_container_scan:
-#  image:
-#    name: docker.io/aquasec/trivy:latest
-#    entrypoint: [""]
-#  variables:
-#    # No need to clone the repo, we exclusively work on artifacts. See
-#    # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
-#    GIT_STRATEGY: none
-#    TRIVY_USERNAME: "$CI_REGISTRY_USER"
-#    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
-#    TRIVY_AUTH_URL: "$CI_REGISTRY"
-#    TRIVY_NO_PROGRESS: "true"
-#    TRIVY_CACHE_DIR: ".trivycache/"
-#    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
-#  script:
-#    - trivy --version
-#    # update vulnerabilities db
-#    - time trivy image --download-db-only
-#    # Builds report and puts it in the default workdir $CI_PROJECT_DIR, so `artifacts:` can take it from there
-#    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl"
-#        --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
-#    # Prints full report
-#    - time trivy image --exit-code 0 "$FULL_IMAGE_NAME"
-#    # Fail on critical vulnerabilities
-#    - time trivy image --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
-#  cache:
-#    paths:
-#      - .trivycache/
-#  # Enables https://docs.gitlab.com/ee/user/application_security/container_scanning/ (Container Scanning report is available on GitLab EE Ultimate or GitLab.com Gold)
-#  artifacts:
-#    when: always
-#    name: gl-container-scanning-report.json
-#    paths:
-#      - gl-container-scanning-report.json
-#    reports:
-#      container_scanning: gl-container-scanning-report.json
-#  stage: test
-#
-#gitleaks_secret_detection:
-#  stage: test
-#  image:
-#    name: zricethezav/gitleaks:latest
-#    entrypoint: [""]
-#  script:
-#    - gitleaks dir . --report-path gitleaks-report.json
-#  artifacts:
-#    when: always
-#    paths:
-#      - gitleaks-report.json
-#
-#deploy_dev:
-#  stage: deploy
-#  when: manual
-#  script:
-#    - echo "Deploying the application..."
-##    здесь будет кастомная логика. в самом простом виде
-##     - ssh $HOST:$USER \
-##     && cd $PATH_TO_PROJECT \
-##     && git pull \
-##     && bin/console bin/console clear:cache \
-##     && bin/console doctrine:migration:migrate
-##  в более продвинутом варианте подменяем контейнер на сервере сбилженным image'м
-#    - echo "Application successfully deployed."
-#
-#deploy_prod:
-#  stage: deploy
-#  when: manual
-#  only:
-#    - tags
-#  script:
-#    - echo "Deploying the application..."
-#    #    здесь будет кастомная логика. в самом простом виде
-#    #     - ssh $HOST:$USER \
-#    #     && cd $PATH_TO_PROJECT \
-#    #     && git pull \
-#    #     && bin/console bin/console clear:cache \
-#    #     && bin/console doctrine:migration:migrate
-#    #  в более продвинутом варианте подменяем контейнер на сервере сбилженным image'м
-#    - echo "Application successfully deployed."
-#
-#dast_nuclei:
-#  stage: DAST
-#  image: golang:latest
-#  variables:
-#    TARGET_URL: https://your-app/
-#  before_script:
-#    - go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
-#  script:
-#    - echo "Target url" $TARGET_URL
-#    - curl -I $TARGET_URL || echo "Target is unreachable"
-#    - nuclei -u $TARGET_URL -jsonl nuclei-report.jsonl || true
-#  artifacts:
-#    when: always
-#    paths:
-#      - nuclei-report.jsonl
+
+migrations_rollback_test:
+  stage: test
+  image: $DEV_IMAGE
+  services:
+    - name: postgres:14
+      alias: postgres
+  variables:
+    APP_ENV: test
+    DATABASE_URL: "pgsql://postgres:postgres@postgres:5432/test_db"
+    POSTGRES_DB: test_db
+    POSTGRES_USER: postgres
+    POSTGRES_PASSWORD: postgres
+    GIT_STRATEGY: none
+  script:
+    - apt-get update && apt-get install -y postgresql-client
+    - until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done
+    - bin/console doctrine:database:create --if-not-exists --env=test
+    - bin/console doctrine:migrations:migrate --no-interaction --env=test
+    - bin/console doctrine:migrations:migrate first --no-interaction --env=test
+    - bin/console doctrine:migrations:migrate --no-interaction --env=test
+
+phpmd:
+  stage: test
+  image: $DEV_IMAGE
+  variables:
+    GIT_STRATEGY: none
+  script:
+    - vendor/bin/phpmd src json phpmd.xml --reportfile phpmd_result.json
+  artifacts:
+    when: always
+    paths:
+      - phpmd_result.json
+
+deptrac:
+  variables:
+    GIT_STRATEGY: none
+  stage: test
+  image: $DEV_IMAGE
+  script:
+    - vendor/bin/deptrac --config-file=deptrac.modules.yaml --cache-file=var/.deptrac.modules.cache
+    - vendor/bin/deptrac --config-file=deptrac.directories.yaml --cache-file=var/.deptrac.directories.cache
+
+kics-iac-scan:
+  stage: test
+  image:
+    name: checkmarx/kics:latest
+    entrypoint: [""]
+  script:
+    - kics scan --no-progress -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results
+  artifacts:
+    when: always
+    name: kics-results.json
+    paths:
+      - kics-results.json
+
+trivy_container_scan:
+  image:
+    name: docker.io/aquasec/trivy:latest
+    entrypoint: [""]
+  variables:
+    # No need to clone the repo, we exclusively work on artifacts. See
+    # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
+    GIT_STRATEGY: none
+    TRIVY_USERNAME: "$CI_REGISTRY_USER"
+    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
+    TRIVY_AUTH_URL: "$CI_REGISTRY"
+    TRIVY_NO_PROGRESS: "true"
+    TRIVY_CACHE_DIR: ".trivycache/"
+    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
+  script:
+    - trivy --version
+    # update vulnerabilities db
+    - time trivy image --download-db-only
+    # Builds report and puts it in the default workdir $CI_PROJECT_DIR, so `artifacts:` can take it from there
+    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl"
+        --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
+    # Prints full report
+    - time trivy image --exit-code 0 "$FULL_IMAGE_NAME"
+    # Fail on critical vulnerabilities
+    - time trivy image --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
+  cache:
+    paths:
+      - .trivycache/
+  # Enables https://docs.gitlab.com/ee/user/application_security/container_scanning/ (Container Scanning report is available on GitLab EE Ultimate or GitLab.com Gold)
+  artifacts:
+    when: always
+    name: gl-container-scanning-report.json
+    paths:
+      - gl-container-scanning-report.json
+    reports:
+      container_scanning: gl-container-scanning-report.json
+  stage: test
+
+gitleaks_secret_detection:
+  stage: test
+  image:
+    name: zricethezav/gitleaks:latest
+    entrypoint: [""]
+  script:
+    - gitleaks dir . --report-path gitleaks-report.json
+  artifacts:
+    when: always
+    paths:
+      - gitleaks-report.json
+
+deploy_dev:
+  stage: deploy
+  when: manual
+  script:
+    - echo "Deploying the application..."
+#    здесь будет кастомная логика. в самом простом виде
+#     - ssh $HOST:$USER \
+#     && cd $PATH_TO_PROJECT \
+#     && git pull \
+#     && bin/console bin/console clear:cache \
+#     && bin/console doctrine:migration:migrate
+#  в более продвинутом варианте подменяем контейнер на сервере сбилженным image'м
+    - echo "Application successfully deployed."
+
+deploy_prod:
+  stage: deploy
+  when: manual
+  only:
+    - tags
+  script:
+    - echo "Deploying the application..."
+    #    здесь будет кастомная логика. в самом простом виде
+    #     - ssh $HOST:$USER \
+    #     && cd $PATH_TO_PROJECT \
+    #     && git pull \
+    #     && bin/console bin/console clear:cache \
+    #     && bin/console doctrine:migration:migrate
+    #  в более продвинутом варианте подменяем контейнер на сервере сбилженным image'м
+    - echo "Application successfully deployed."
+
+dast_nuclei:
+  stage: DAST
+  image: golang:latest
+  variables:
+    TARGET_URL: https://your-app/
+  before_script:
+    - go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
+  script:
+    - echo "Target url" $TARGET_URL
+    - curl -I $TARGET_URL || echo "Target is unreachable"
+    - nuclei -u $TARGET_URL -jsonl nuclei-report.jsonl || true
+  artifacts:
+    when: always
+    paths:
+      - nuclei-report.jsonl
